# name: CI #自动化的名称
# on:
#   push: # push的时候触发
#     branches: # 那些分支需要触发
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest # 镜像市场
#     steps:
#       - name: checkout # 步骤的名称.
#         uses: actions/checkout@v1 #软件市场的名称
#         with: # 参数
#           submodules: true
#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2.2.2
#         with:
#           hugo-version: '0.64.1'
#           extended: true
#       - name: Build
#         run: hugo -D
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v2.5.1
#         env:
#           ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#           EXTERNAL_REPOSITORY: redisread/redisread.github.io
#           PUBLISH_BRANCH: master
#           PUBLISH_DIR: ./public
      # - name: Deploy_Huawei
      #   env:
      #     ACTIONS_DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY_KEY }}
      #     HOST: ${{ secrets.SSH_HOST }}
      #     USER: ${{ secrets.SSH_USERNAME }}
      #   run: |
      #     cd /root/github/HUGO_blog
      #     git pull
      #     hugo -D
      # - name: Deploy_Huawei
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:
      #     username: ${{ secrets.SSH_USERNAME }}
      #     server: ${{ secrets.SSH_HOST }}
      #     ssh_private_key: ${{ secrets.HUGO_DEPLOY_KEY }}
      #     local_path: ./public
      #     remote_path: /usr/local/nginx/html/hugo_blog #服务器部署路

name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.1"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: redisread/redisread.github.io
          publish_dir: ./public
          #   keep_files: true
          # user_name: <username>
          # user_email: <username@email.com>
          publish_branch: master
        #   cname: example.com